/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Process is up. Deliberately touches no dependency.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Dependencies are reachable. Returns 503 when any of them is not.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and start a session */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh cookie and mint a new access token */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin the GitHub authorization-code flow */
        get: operations["github_login_auth_github_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete the GitHub flow and start a session
         * @description Set the refresh cookie and bounce back to the SPA.
         *
         *     No token is placed in the redirect URL: the browser lands on the frontend
         *     with only the httpOnly cookie, and the SPA calls `/auth/refresh` to obtain
         *     its first access token. That keeps credentials out of history and referrers.
         */
        get: operations["github_callback_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organizations the caller belongs to */
        get: operations["list_orgs_orgs_get"];
        put?: never;
        /** Create an organization owned by the caller */
        post: operations["create_org_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members of an organization */
        get: operations["list_members_orgs__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite someone to an organization
         * @description Admins may invite; only an owner may hand out the owner role.
         */
        post: operations["invite_member_orgs__org_id__invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invitation */
        post: operations["accept_invite_orgs_invites__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{org_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys (never their secrets) */
        get: operations["list_api_keys_orgs__org_id__api_keys_get"];
        put?: never;
        /** Create an API key (the secret is shown exactly once) */
        post: operations["create_api_key_orgs__org_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Owner-only, and scoped by org via the `org_id` query parameter, so a
         *     guessed key id belonging to another tenant 404s rather than being revoked.
         */
        delete: operations["revoke_api_key_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an organization's monitors */
        get: operations["list_monitors_monitors_get"];
        put?: never;
        /**
         * Create a monitor (accepts a bearer token or an X-API-Key header)
         * @description Scriptable: a CI job can create monitors with an API key and no session.
         */
        post: operations["create_monitor_monitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one monitor */
        get: operations["get_monitor_monitors__monitor_id__get"];
        put?: never;
        post?: never;
        /** Delete a monitor and its check history */
        delete: operations["delete_monitor_monitors__monitor_id__delete"];
        options?: never;
        head?: never;
        /** Update a monitor */
        patch: operations["update_monitor_monitors__monitor_id__patch"];
        trace?: never;
    };
    "/monitors/{monitor_id}/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one check immediately
         * @description Probe synchronously and persist the result.
         *
         *     Phase 3 moves scheduled checks onto a worker; this endpoint stays as the
         *     manual "test it now" path, which is worth keeping synchronous so the user
         *     sees the outcome straight away.
         */
        post: operations["run_now_monitors__monitor_id__run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated check history, newest first */
        get: operations["list_checks_monitors__monitor_id__checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a monitor */
        post: operations["pause_monitor_monitors__monitor_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{monitor_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a monitor */
        post: operations["resume_monitor_monitors__monitor_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents for an org */
        get: operations["list_incidents_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One incident with its timeline */
        get: operations["get_incident_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post an update to an incident's timeline */
        post: operations["post_update_incidents__incident_id__updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve an incident manually */
        post: operations["resolve_incidents__incident_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notification channels */
        get: operations["list_channels_channels_get"];
        put?: never;
        /** Add a notification channel */
        post: operations["create_channel_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a channel */
        delete: operations["delete_channel_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Update a channel */
        patch: operations["update_channel_channels__channel_id__patch"];
        trace?: never;
    };
    "/channels/{channel_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test notification
         * @description Deliver synchronously so the user gets immediate feedback.
         *
         *     This is the one place a notification is *not* queued: someone configuring a
         *     webhook needs to know right now whether it works, and a background job that
         *     silently fails would be useless feedback.
         */
        post: operations["test_channel_channels__channel_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List status pages */
        get: operations["list_status_pages_status_pages_get"];
        put?: never;
        /** Create a status page */
        post: operations["create_status_page_status_pages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status-pages/{page_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a status page */
        delete: operations["delete_status_page_status_pages__page_id__delete"];
        options?: never;
        head?: never;
        /** Update a status page */
        patch: operations["update_status_page_status_pages__page_id__patch"];
        trace?: never;
    };
    "/monitors/{monitor_id}/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Uptime and p95 latency over a window
         * @description Uptime over a window, read from hourly rollups rather than raw rows.
         *
         *     Rollups cover every closed hour; the still-open hour is added from
         *     `check_results`, so the figure stays current without scanning the window.
         */
        get: operations["monitor_uptime_monitors__monitor_id__uptime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/status/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public status page (no authentication)
         * @description Anonymous view of a published status page.
         *
         *     This route takes **no** auth dependency and returns a schema written for
         *     this endpoint alone — never `MonitorRead` — so no internal field can leak
         *     by being added to a model later.
         */
        get: operations["public_status_page_public_status__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /** Name */
            name: string;
        };
        /**
         * ApiKeyCreated
         * @description The only response that ever contains the raw key.
         */
        ApiKeyCreated: {
            key: components["schemas"]["ApiKeyRead"];
            /**
             * Secret
             * @description Shown once. Only a hash is stored, so it cannot be retrieved again.
             */
            secret: string;
        };
        /** ApiKeyRead */
        ApiKeyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Assertions
         * @description What must hold for a check to count as `ok`.
         *
         *     An empty object means "any 2xx/3xx response passes". This exact shape is the
         *     contract shared by the checker, the API and the frontend's form.
         */
        Assertions: {
            /** Status Code */
            status_code?: number | null;
            /** Max Latency Ms */
            max_latency_ms?: number | null;
            /** Body Contains */
            body_contains?: string | null;
            /** Body Not Contains */
            body_not_contains?: string | null;
        };
        /** ChannelCreate */
        ChannelCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["ChannelType"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /**
         * ChannelRead
         * @description Read shape — `config` is always masked on the way out.
         */
        ChannelRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            type: components["schemas"]["ChannelType"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChannelTestResult */
        ChannelTestResult: {
            /**
             * Delivered
             * @enum {boolean}
             */
            delivered: true | false;
            /** Detail */
            detail?: string | null;
        };
        /**
         * ChannelType
         * @enum {string}
         */
        ChannelType: "email" | "slack" | "discord";
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * CheckPage
         * @description Cursor-paginated check history.
         *
         *     The cursor is the `checked_at` of the last row, which pairs with the
         *     `(monitor_id, checked_at)` index — unlike OFFSET, it stays fast deep into
         *     the history.
         */
        CheckPage: {
            /** Items */
            items: components["schemas"]["CheckResultRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** CheckResultRead */
        CheckResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Ok */
            ok: boolean;
            /** Status Code */
            status_code: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Error */
            error: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IncidentDetail */
        IncidentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Resolved At */
            resolved_at: string | null;
            severity: components["schemas"]["IncidentSeverity"];
            /** Cause */
            cause: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Monitor Name */
            monitor_name?: string | null;
            /** Updates */
            updates?: components["schemas"]["IncidentUpdateRead"][];
        };
        /** IncidentRead */
        IncidentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Monitor Id
             * Format: uuid
             */
            monitor_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Resolved At */
            resolved_at: string | null;
            severity: components["schemas"]["IncidentSeverity"];
            /** Cause */
            cause: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Monitor Name */
            monitor_name?: string | null;
        };
        /**
         * IncidentSeverity
         * @enum {string}
         */
        IncidentSeverity: "minor" | "major" | "critical";
        /** IncidentUpdateCreate */
        IncidentUpdateCreate: {
            /** Message */
            message: string;
        };
        /** IncidentUpdateRead */
        IncidentUpdateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /** Message */
            message: string;
            /** Created By */
            created_by: string | null;
            /** Is Auto */
            is_auto: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InviteCreate */
        InviteCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default viewer */
            role: components["schemas"]["MemberRole"];
        };
        /**
         * InviteCreated
         * @description The raw token is returned exactly once, at creation.
         *
         *     Only its digest is stored, so this response (and the emailed link) is the
         *     single opportunity to capture it.
         */
        InviteCreated: {
            invite: components["schemas"]["InviteRead"];
            /** Accept Url */
            accept_url: string;
        };
        /** InviteRead */
        InviteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Email */
            email: string;
            role: components["schemas"]["MemberRole"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Accepted At */
            accepted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MemberRead */
        MemberRead: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            role: components["schemas"]["MemberRole"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /**
         * MemberRole
         * @description Roles, least to most privileged.
         *
         *     Comparison is by `RANK` rather than by declaration order so that inserting a
         *     new role later cannot silently change who is allowed to do what.
         * @enum {string}
         */
        MemberRole: "viewer" | "admin" | "owner";
        /** MonitorCreate */
        MonitorCreate: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Method
             * @default GET
             * @enum {string}
             */
            method: "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS";
            /**
             * Interval S
             * @default 60
             */
            interval_s: number;
            /**
             * Timeout Ms
             * @default 5000
             */
            timeout_ms: number;
            assertions?: components["schemas"]["Assertions"];
        };
        /** MonitorRead */
        MonitorRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Method */
            method: string;
            /** Interval S */
            interval_s: number;
            /** Timeout Ms */
            timeout_ms: number;
            assertions: components["schemas"]["Assertions"];
            /** Is Active */
            is_active: boolean;
            /**
             * Next Run At
             * Format: date-time
             */
            next_run_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["MonitorStatus"];
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Last Checked At */
            last_checked_at: string | null;
        };
        /**
         * MonitorStatus
         * @enum {string}
         */
        MonitorStatus: "unknown" | "up" | "down";
        /**
         * MonitorUpdate
         * @description PATCH body. Every field optional; omitted fields are left untouched.
         */
        MonitorUpdate: {
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
            /** Method */
            method?: ("GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS") | null;
            /** Interval S */
            interval_s?: number | null;
            /** Timeout Ms */
            timeout_ms?: number | null;
            assertions?: components["schemas"]["Assertions"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** OrgCreate */
        OrgCreate: {
            /** Name */
            name: string;
            /**
             * Slug
             * @description URL-safe identifier. Derived from the name when omitted.
             */
            slug?: string | null;
        };
        /** OrgRead */
        OrgRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrgSummary
         * @description An organization plus the caller's own role in it.
         */
        OrgSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            role: components["schemas"]["MemberRole"];
        };
        /**
         * PublicDay
         * @description One cell of the uptime bar.
         */
        PublicDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * State
             * @enum {string}
             */
            state: "up" | "degraded" | "down" | "no_data";
            /** Uptime Pct */
            uptime_pct: number;
        };
        /**
         * PublicIncident
         * @description An incident as shown publicly — no internal ids, no raw check errors.
         */
        PublicIncident: {
            /** Monitor Name */
            monitor_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Updates */
            updates: components["schemas"]["PublicIncidentUpdate"][];
        };
        /** PublicIncidentUpdate */
        PublicIncidentUpdate: {
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PublicMonitor
         * @description What an anonymous visitor may see about a monitor.
         *
         *     Note what is absent: the target `url`, the `org_id`, the assertions, the
         *     interval, and the monitor's real id. A visitor gets a display name, a
         *     traffic light, and a history bar.
         */
        PublicMonitor: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "operational" | "degraded" | "down" | "unknown";
            /** Uptime 90D */
            uptime_90d: number;
            /** Days */
            days: components["schemas"]["PublicDay"][];
        };
        /** PublicStatusPage */
        PublicStatusPage: {
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Overall
             * @enum {string}
             */
            overall: "operational" | "degraded" | "down" | "unknown";
            /** Monitors */
            monitors: components["schemas"]["PublicMonitor"][];
            /** Incidents */
            incidents: components["schemas"]["PublicIncident"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Redis */
            redis: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Message
             * @default Resolved manually.
             */
            message: string;
        };
        /** StatusPageCreate */
        StatusPageCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Monitor Ids */
            monitor_ids?: string[];
        };
        /**
         * StatusPageRead
         * @description Admin view — safe to include ids, since the caller is a member.
         */
        StatusPageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Is Published */
            is_published: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Monitor Ids */
            monitor_ids?: string[];
            /** Public Url */
            public_url: string;
        };
        /** StatusPageUpdate */
        StatusPageUpdate: {
            /** Title */
            title?: string | null;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Is Published */
            is_published?: boolean | null;
            /** Monitor Ids */
            monitor_ids?: string[] | null;
        };
        /**
         * TokenResponse
         * @description The refresh token is not in this body — it is set as an httpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds.
             */
            expires_in: number;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pb_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                pb_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    github_login_auth_github_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    github_callback_auth_github_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orgs_orgs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSummary"][];
                };
            };
        };
    };
    create_org_orgs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_orgs__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_member_orgs__org_id__invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_orgs_invites__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_orgs__org_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_orgs__org_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_keys__key_id__delete: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monitors_monitors_get: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_monitor_monitors_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monitor_monitors__monitor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_monitor_monitors__monitor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_monitors__monitor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_monitors__monitor_id__run_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checks_monitors__monitor_id__checks_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_monitor_monitors__monitor_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_monitor_monitors__monitor_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_incidents_get: {
        parameters: {
            query: {
                status?: ("open" | "resolved") | null;
                monitor_id?: string | null;
                limit?: number;
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_incidents__incident_id__get: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_update_incidents__incident_id__updates_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentUpdateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentUpdateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_incidents__incident_id__resolve_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_channels_get: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_channels_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_channels__channel_id__delete: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_channels__channel_id__patch: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_channel_channels__channel_id__test_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_status_pages_status_pages_get: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_status_page_status_pages_post: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_status_page_status_pages__page_id__delete: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_page_status_pages__page_id__patch: {
        parameters: {
            query: {
                /** @description Organization that owns the resource */
                org_id: string;
            };
            header?: never;
            path: {
                page_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusPageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusPageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitor_uptime_monitors__monitor_id__uptime_get: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                monitor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_status_page_public_status__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatusPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
