"""Incident and incident-update models."""

from __future__ import annotations

import enum
from datetime import datetime
from uuid import UUID

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    String,
    Text,
    Uuid,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db import Base
from app.core.mixins import TimestampMixin, UUIDMixin


class IncidentSeverity(enum.StrEnum):
    MINOR = "minor"
    MAJOR = "major"
    CRITICAL = "critical"


severity_enum = Enum(
    IncidentSeverity,
    name="incident_severity",
    values_callable=lambda enum_cls: [member.value for member in enum_cls],
)


class Incident(UUIDMixin, TimestampMixin, Base):
    """An outage window for one monitor.

    At most one incident per monitor may be open at a time; the partial unique
    index below enforces that in the database rather than trusting application
    logic, because the worker can race with a manual resolve.
    """

    __tablename__ = "incidents"
    __table_args__ = (
        Index(
            "uq_incidents_one_open_per_monitor",
            "monitor_id",
            unique=True,
            postgresql_where=text("resolved_at IS NULL"),
        ),
        Index("ix_incidents_monitor_started", "monitor_id", "started_at"),
    )

    monitor_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("monitors.id", ondelete="CASCADE"), nullable=False
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    severity: Mapped[IncidentSeverity] = mapped_column(
        severity_enum, nullable=False, server_default=IncidentSeverity.MAJOR.value
    )
    # Snapshot of the failure that opened the incident. Kept here so the
    # incident still explains itself after the raw check rows are pruned.
    cause: Mapped[str | None] = mapped_column(Text)

    updates: Mapped[list[IncidentUpdate]] = relationship(
        back_populates="incident",
        cascade="all, delete",
        passive_deletes=True,
        lazy="raise",
        order_by="IncidentUpdate.created_at",
    )

    @property
    def is_open(self) -> bool:
        return self.resolved_at is None


class IncidentUpdate(UUIDMixin, TimestampMixin, Base):
    """A timeline entry — either written by a person or generated by the worker."""

    __tablename__ = "incident_updates"

    incident_id: Mapped[UUID] = mapped_column(
        Uuid, ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, index=True
    )
    message: Mapped[str] = mapped_column(String(2000), nullable=False)
    # Null for automated entries, and for people who later delete their account.
    created_by: Mapped[UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL")
    )
    is_auto: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    incident: Mapped[Incident] = relationship(back_populates="updates")
    author: Mapped[object | None] = relationship("User", lazy="raise")
