"""status pages

Revision ID: 02af51067fca
Revises: 599599770f45
Create Date: 2026-10-05 12:28:38.037584

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "02af51067fca"
down_revision: str | None = "599599770f45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_pages",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_status_pages_org_id"), "status_pages", ["org_id"], unique=False)
    op.create_index(op.f("ix_status_pages_slug"), "status_pages", ["slug"], unique=True)
    op.create_table(
        "status_page_monitors",
        sa.Column("status_page_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_page_id"], ["status_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("status_page_id", "monitor_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("status_page_monitors")
    op.drop_index(op.f("ix_status_pages_slug"), table_name="status_pages")
    op.drop_index(op.f("ix_status_pages_org_id"), table_name="status_pages")
    op.drop_table("status_pages")
    # ### end Alembic commands ###
